
title: 5C4T3R - Smart Contract Security Engineer
email: 0xscater@gmail.com
description: >-
  Smart Contract CTF Writeups, Exploits, and Security Research(Blockchain, Solidity, EVM, Ethereum, Audits, Vulnerabilities, and more))

baseurl: "" 
url: "https://BLOCK-PROGRAMR.github.io" 

plugins:
  - jekyll-feed
  # - jekyll-tagging

collections:
  projects:
    output: true
    permalink: /projects/:title/
  analysis:
    output: true
    permalink: /analysis/:title/
  audits:
    output: true
    permalink: /audits/:title/

tag_permalink_style: pretty

tag_page_layout: tag
tag_page_dir: tag
taxonomies:
  tag: tags
  
theme: minima
show_excerpts: true

social_links:
  github: BLOCK-PROGRAMR
  twitter: 0x_Scater

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


